-- Rozwiązanie zadań SQL (OpenOffice / LibreOffice Base)
-- Wersja poprawiona tak, żeby wykonywała się "od zera" i żeby SELECT-y działały.
-- Najważniejsze poprawki:
--  - literały dat: {d 'YYYY-MM-DD'} (zamiast DATE 'YYYY-MM-DD')
--  - nazwy tabel/kolumn zapisane UPPER CASE (zgodnie z zachowaniem silnika Base)
--  - YEAR() zastąpione przez EXTRACT(YEAR FROM ...)
--
-- Uwaga: skrypt zakłada pustą bazę. Jeśli tabele już istnieją, usuń je ręcznie w GUI Base
-- albo dodaj DROP TABLE w odpowiedniej kolejności (zależnie od silnika może wymagać CASCADE).

-- ============================================================
-- Zadanie 1: CREATE TABLE (bez pól PREMIA i SPECJALIZACJA)
-- ============================================================

CREATE TABLE DZIALY (
    NR_DZIALU INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAZWA VARCHAR(100) NOT NULL,
    LOKALIZACJA VARCHAR(100) NOT NULL,
    SZEF_DZIALU INTEGER
);

CREATE TABLE ZESPOLY (
    NR_ZESPOLU INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAZWA_ZESPOLU VARCHAR(100) NOT NULL,
    DATA_POWOLANIA DATE NOT NULL,
    BUDZET DECIMAL(12,2) NOT NULL,
    KIEROWNIK INTEGER,
    NR_DZIALU INTEGER,
    CONSTRAINT FK_ZESPOLY_DZIALY FOREIGN KEY (NR_DZIALU) REFERENCES DZIALY(NR_DZIALU)
);

CREATE TABLE PRACOWNICY (
    NR_PRAC INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IMIE VARCHAR(80) NOT NULL,
    NAZWISKO VARCHAR(80) NOT NULL,
    STANOWISKO VARCHAR(80) NOT NULL,
    ZAROBKI DECIMAL(10,2) NOT NULL,
    DATA_ZATRUDNIENIA DATE NOT NULL,
    NR_ZESPOLU INTEGER,
    CONSTRAINT FK_PRACOWNICY_ZESPOLY FOREIGN KEY (NR_ZESPOLU) REFERENCES ZESPOLY(NR_ZESPOLU)
);

ALTER TABLE DZIALY
    ADD CONSTRAINT FK_DZIALY_SZEF FOREIGN KEY (SZEF_DZIALU) REFERENCES PRACOWNICY(NR_PRAC);

ALTER TABLE ZESPOLY
    ADD CONSTRAINT FK_ZESPOLY_KIEROWNIK FOREIGN KEY (KIEROWNIK) REFERENCES PRACOWNICY(NR_PRAC);


-- ============================================================
-- Zadanie 2: Dodanie pól PREMIA i SPECJALIZACJA
-- ============================================================

ALTER TABLE PRACOWNICY ADD PREMIA DECIMAL(10,2) DEFAULT 0;
ALTER TABLE ZESPOLY ADD SPECJALIZACJA VARCHAR(120);


-- ============================================================
-- Zadanie 3: Wstawienie co najmniej 3 rekordów do każdej tabeli
-- ============================================================

-- Najpierw działy i zespoły (bez szefów/kierowników), potem pracownicy,
-- na końcu aktualizacja kluczy obcych zależnych od pracowników.

INSERT INTO DZIALY (NAZWA, LOKALIZACJA, SZEF_DZIALU) VALUES ('IT', 'Szczecin', NULL);
INSERT INTO DZIALY (NAZWA, LOKALIZACJA, SZEF_DZIALU) VALUES ('Administracja', 'Warszawa', NULL);
INSERT INTO DZIALY (NAZWA, LOKALIZACJA, SZEF_DZIALU) VALUES ('Marketing', 'Gdansk', NULL);

INSERT INTO ZESPOLY (NAZWA_ZESPOLU, DATA_POWOLANIA, BUDZET, KIEROWNIK, NR_DZIALU, SPECJALIZACJA)
VALUES ('Backend', {d '2018-03-01'}, 25000.00, NULL, 1, 'Systemy serwerowe');
INSERT INTO ZESPOLY (NAZWA_ZESPOLU, DATA_POWOLANIA, BUDZET, KIEROWNIK, NR_DZIALU, SPECJALIZACJA)
VALUES ('Frontend', {d '2020-06-15'}, 12000.00, NULL, 1, 'Interfejsy webowe');
INSERT INTO ZESPOLY (NAZWA_ZESPOLU, DATA_POWOLANIA, BUDZET, KIEROWNIK, NR_DZIALU, SPECJALIZACJA)
VALUES ('HR-Operacje', {d '2017-01-10'}, 8000.00, NULL, 2, 'Kadry');
INSERT INTO ZESPOLY (NAZWA_ZESPOLU, DATA_POWOLANIA, BUDZET, KIEROWNIK, NR_DZIALU, SPECJALIZACJA)
VALUES ('Samodzielni', {d '2022-02-01'}, 4000.00, NULL, NULL, 'Eksperci niezalezni');

INSERT INTO PRACOWNICY (IMIE, NAZWISKO, STANOWISKO, ZAROBKI, DATA_ZATRUDNIENIA, NR_ZESPOLU, PREMIA)
VALUES ('Jan', 'Kowalski', 'kierownik zespolu', 8200.00, {d '2016-02-12'}, 1, 800.00);
INSERT INTO PRACOWNICY (IMIE, NAZWISKO, STANOWISKO, ZAROBKI, DATA_ZATRUDNIENIA, NR_ZESPOLU, PREMIA)
VALUES ('Anna', 'Nowak', 'kierownik zespolu', 7800.00, {d '2022-01-15'}, 2, 600.00);
INSERT INTO PRACOWNICY (IMIE, NAZWISKO, STANOWISKO, ZAROBKI, DATA_ZATRUDNIENIA, NR_ZESPOLU, PREMIA)
VALUES ('Piotr', 'Zielinski', 'programista', 5600.00, {d '2019-07-22'}, 1, 400.00);
INSERT INTO PRACOWNICY (IMIE, NAZWISKO, STANOWISKO, ZAROBKI, DATA_ZATRUDNIENIA, NR_ZESPOLU, PREMIA)
VALUES ('Maria', 'Wisniewska', 'kierownik zespolu', 7600.00, {d '2015-11-03'}, 3, 700.00);
INSERT INTO PRACOWNICY (IMIE, NAZWISKO, STANOWISKO, ZAROBKI, DATA_ZATRUDNIENIA, NR_ZESPOLU, PREMIA)
VALUES ('Tomasz', 'Lewandowski', 'analityk', 4900.00, {d '2021-09-20'}, 2, 300.00);
INSERT INTO PRACOWNICY (IMIE, NAZWISKO, STANOWISKO, ZAROBKI, DATA_ZATRUDNIENIA, NR_ZESPOLU, PREMIA)
VALUES ('Karolina', 'Wojcik', 'specjalista HR', 4700.00, {d '2014-05-18'}, 3, 250.00);
INSERT INTO PRACOWNICY (IMIE, NAZWISKO, STANOWISKO, ZAROBKI, DATA_ZATRUDNIENIA, NR_ZESPOLU, PREMIA)
VALUES ('Pawel', 'Kaczmarek', 'konsultant', 5100.00, {d '2023-04-02'}, NULL, 150.00);

-- Ustawienie kierowników zespołów
UPDATE ZESPOLY SET KIEROWNIK = 1 WHERE NR_ZESPOLU = 1;
UPDATE ZESPOLY SET KIEROWNIK = 2 WHERE NR_ZESPOLU = 2;
UPDATE ZESPOLY SET KIEROWNIK = 4 WHERE NR_ZESPOLU = 3;
UPDATE ZESPOLY SET KIEROWNIK = 7 WHERE NR_ZESPOLU = 4;

-- Ustawienie szefów działów
UPDATE DZIALY SET SZEF_DZIALU = 1 WHERE NR_DZIALU = 1;
UPDATE DZIALY SET SZEF_DZIALU = 4 WHERE NR_DZIALU = 2;
UPDATE DZIALY SET SZEF_DZIALU = 2 WHERE NR_DZIALU = 3;


-- ============================================================
-- Zadanie 4: Usunięcie pola SPECJALIZACJA z tabeli ZESPOLY
-- ============================================================

ALTER TABLE ZESPOLY DROP SPECJALIZACJA;


-- ============================================================
-- Zadanie 5: Usunięcie po 1 rekordzie z dwóch tabel
-- ============================================================

-- Usunięcie 1 rekordu z PRACOWNICY (osoba bez roli kierownika/szefa)
DELETE FROM PRACOWNICY WHERE NR_PRAC = 5;

-- Usunięcie 1 rekordu z ZESPOLY (zespół samodzielny, bez przypisanego działu)
DELETE FROM ZESPOLY WHERE NR_ZESPOLU = 4;


-- ============================================================
-- Zadania SELECT (6-15)
-- ============================================================

-- 6) Imiona i nazwiska pracowników zarabiających co najmniej 4489.34 zł
SELECT IMIE, NAZWISKO
FROM PRACOWNICY
WHERE ZAROBKI >= 4489.34;

-- 7) Lista pracowników z nazwami przypisanych zespołów
SELECT P.IMIE, P.NAZWISKO, Z.NAZWA_ZESPOLU
FROM PRACOWNICY P
LEFT JOIN ZESPOLY Z ON Z.NR_ZESPOLU = P.NR_ZESPOLU;

-- 8) Lista działów wraz z nazwiskami ich szefów
SELECT D.NAZWA AS DZIAL, P.NAZWISKO AS SZEF
FROM DZIALY D
JOIN PRACOWNICY P ON P.NR_PRAC = D.SZEF_DZIALU;

-- 9) Nazwy działów bez przyporządkowanego zespołu
SELECT D.NAZWA
FROM DZIALY D
LEFT JOIN ZESPOLY Z ON Z.NR_DZIALU = D.NR_DZIALU
WHERE Z.NR_ZESPOLU IS NULL;

-- 10) Nazwiska pracowników niebędących szefem żadnego działu
SELECT P.NAZWISKO
FROM PRACOWNICY P
LEFT JOIN DZIALY D ON D.SZEF_DZIALU = P.NR_PRAC
WHERE D.NR_DZIALU IS NULL;

-- 11) Nazwiska i zarobki kierowników zespołów zatrudnionych po roku {X1}
-- Przykład: X1 = 2001
SELECT P.NAZWISKO, P.ZAROBKI
FROM PRACOWNICY P
JOIN ZESPOLY Z ON Z.KIEROWNIK = P.NR_PRAC
WHERE EXTRACT(YEAR FROM P.DATA_ZATRUDNIENIA) > 2001;

-- 12) Nazwiska osób będących jednocześnie kierownikiem zespołu i szefem działu
SELECT DISTINCT P.NAZWISKO
FROM PRACOWNICY P
JOIN ZESPOLY Z ON Z.KIEROWNIK = P.NR_PRAC
JOIN DZIALY D ON D.SZEF_DZIALU = P.NR_PRAC;

-- 13) Imiona i nazwiska osób w zespołach o budżecie > {X2}
-- Przykład: X2 = 16000
SELECT P.IMIE, P.NAZWISKO
FROM PRACOWNICY P
JOIN ZESPOLY Z ON Z.NR_ZESPOLU = P.NR_ZESPOLU
WHERE Z.BUDZET > 16000;

-- 14) Osoby doświadczone dla zespołu (zatrudnione przed datą powołania zespołu)
SELECT P.IMIE, P.NAZWISKO, Z.NAZWA_ZESPOLU
FROM PRACOWNICY P
JOIN ZESPOLY Z ON Z.NR_ZESPOLU = P.NR_ZESPOLU
WHERE P.DATA_ZATRUDNIENIA < Z.DATA_POWOLANIA;

-- 15) Osoby na stanowisku {X3} w zespołach z budżetem <= {X4}
-- Przykład: X3 = 'programista', X4 = 3000
SELECT P.IMIE, P.NAZWISKO
FROM PRACOWNICY P
JOIN ZESPOLY Z ON Z.NR_ZESPOLU = P.NR_ZESPOLU
WHERE LOWER(P.STANOWISKO) = LOWER('programista')
  AND Z.BUDZET <= 3000;
