-- Rozwiązanie zadań SQL (OpenOffice / LibreOffice Base)
-- Wersja poprawiona tak, żeby wykonywała się "od zera" i żeby SELECT-y działały.
-- Najważniejsze poprawki:
--  - literały dat: {d 'YYYY-MM-DD'} (zamiast DATE 'YYYY-MM-DD')
--  - brak cudzysłowów w nazwach tabel/kolumn w SELECT (żeby nie było problemu z wielkością liter)
--  - zgodność z częstymi ograniczeniami Base: brak DROP COLUMN (Zadanie 4 zrealizowane przez tabelę zastępczą)
--  - YEAR() zastąpione przez EXTRACT(YEAR FROM ...)
--
-- Uwaga: skrypt zakłada pustą bazę. Jeśli tabele już istnieją, usuń je ręcznie w GUI Base
-- albo dodaj DROP TABLE w odpowiedniej kolejności (zależnie od silnika może wymagać CASCADE).

-- ============================================================
-- Zadanie 1: CREATE TABLE (bez pól Premia i Specjalizacja)
-- ============================================================

CREATE TABLE Dzialy (
    Nr_dzialu INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nazwa VARCHAR(100) NOT NULL UNIQUE,
    Lokalizacja VARCHAR(100) NOT NULL,
    Szef_dzialu INTEGER
);

CREATE TABLE Zespoly (
    Nr_zespolu INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nazwa_zespolu VARCHAR(100) NOT NULL UNIQUE,
    Data_powolania DATE NOT NULL,
    Budzet DECIMAL(12,2) NOT NULL,
    Kierownik INTEGER,
    Nr_dzialu INTEGER,
    CONSTRAINT FK_Zespoly_Dzialy FOREIGN KEY (Nr_dzialu) REFERENCES Dzialy(Nr_dzialu)
);

CREATE TABLE Pracownicy (
    Nr_prac INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Imie VARCHAR(80) NOT NULL,
    Nazwisko VARCHAR(80) NOT NULL,
    Stanowisko VARCHAR(80) NOT NULL,
    Zarobki DECIMAL(10,2) NOT NULL,
    Data_zatrudnienia DATE NOT NULL,
    Nr_zespolu INTEGER,
    CONSTRAINT FK_Pracownicy_Zespoly FOREIGN KEY (Nr_zespolu) REFERENCES Zespoly(Nr_zespolu)
);

ALTER TABLE Dzialy
    ADD CONSTRAINT FK_Dzialy_Szef FOREIGN KEY (Szef_dzialu) REFERENCES Pracownicy(Nr_prac);

ALTER TABLE Zespoly
    ADD CONSTRAINT FK_Zespoly_Kierownik FOREIGN KEY (Kierownik) REFERENCES Pracownicy(Nr_prac);


-- ============================================================
-- Zadanie 2: Dodanie pól Premia i Specjalizacja
-- ============================================================

ALTER TABLE Pracownicy ADD Premia DECIMAL(10,2) DEFAULT 0;
ALTER TABLE Zespoly ADD Specjalizacja VARCHAR(120);


-- ============================================================
-- Zadanie 3: Wstawienie co najmniej 3 rekordów do każdej tabeli
-- ============================================================

-- Najpierw działy i zespoły (bez szefów/kierowników), potem pracownicy,
-- na końcu aktualizacja kluczy obcych zależnych od pracowników.

INSERT INTO Dzialy (Nazwa, Lokalizacja, Szef_dzialu) VALUES ('IT', 'Szczecin', NULL);
INSERT INTO Dzialy (Nazwa, Lokalizacja, Szef_dzialu) VALUES ('Administracja', 'Warszawa', NULL);
INSERT INTO Dzialy (Nazwa, Lokalizacja, Szef_dzialu) VALUES ('Marketing', 'Gdansk', NULL);

INSERT INTO Zespoly (Nazwa_zespolu, Data_powolania, Budzet, Kierownik, Nr_dzialu, Specjalizacja)
VALUES ('Backend', {d '2018-03-01'}, 25000.00, NULL, 1, 'Systemy serwerowe');
INSERT INTO Zespoly (Nazwa_zespolu, Data_powolania, Budzet, Kierownik, Nr_dzialu, Specjalizacja)
VALUES ('Frontend', {d '2020-06-15'}, 12000.00, NULL, 1, 'Interfejsy webowe');
INSERT INTO Zespoly (Nazwa_zespolu, Data_powolania, Budzet, Kierownik, Nr_dzialu, Specjalizacja)
VALUES ('HR-Operacje', {d '2017-01-10'}, 8000.00, NULL, 2, 'Kadry');
INSERT INTO Zespoly (Nazwa_zespolu, Data_powolania, Budzet, Kierownik, Nr_dzialu, Specjalizacja)
VALUES ('Samodzielni', {d '2022-02-01'}, 4000.00, NULL, NULL, 'Eksperci niezalezni');

INSERT INTO Pracownicy (Imie, Nazwisko, Stanowisko, Zarobki, Data_zatrudnienia, Nr_zespolu, Premia)
VALUES ('Jan', 'Kowalski', 'kierownik zespolu', 8200.00, {d '2016-02-12'}, 1, 800.00);
INSERT INTO Pracownicy (Imie, Nazwisko, Stanowisko, Zarobki, Data_zatrudnienia, Nr_zespolu, Premia)
VALUES ('Anna', 'Nowak', 'kierownik zespolu', 7800.00, {d '2022-01-15'}, 2, 600.00);
INSERT INTO Pracownicy (Imie, Nazwisko, Stanowisko, Zarobki, Data_zatrudnienia, Nr_zespolu, Premia)
VALUES ('Piotr', 'Zielinski', 'programista', 5600.00, {d '2019-07-22'}, 1, 400.00);
INSERT INTO Pracownicy (Imie, Nazwisko, Stanowisko, Zarobki, Data_zatrudnienia, Nr_zespolu, Premia)
VALUES ('Maria', 'Wisniewska', 'kierownik zespolu', 7600.00, {d '2015-11-03'}, 3, 700.00);
INSERT INTO Pracownicy (Imie, Nazwisko, Stanowisko, Zarobki, Data_zatrudnienia, Nr_zespolu, Premia)
VALUES ('Tomasz', 'Lewandowski', 'analityk', 4900.00, {d '2021-09-20'}, 2, 300.00);
INSERT INTO Pracownicy (Imie, Nazwisko, Stanowisko, Zarobki, Data_zatrudnienia, Nr_zespolu, Premia)
VALUES ('Karolina', 'Wojcik', 'specjalista HR', 4700.00, {d '2014-05-18'}, 3, 250.00);
INSERT INTO Pracownicy (Imie, Nazwisko, Stanowisko, Zarobki, Data_zatrudnienia, Nr_zespolu, Premia)
VALUES ('Pawel', 'Kaczmarek', 'konsultant', 5100.00, {d '2023-04-02'}, NULL, 150.00);

-- Ustawienie kierowników zespołów
UPDATE Zespoly SET Kierownik = 1 WHERE Nr_zespolu = 1;
UPDATE Zespoly SET Kierownik = 2 WHERE Nr_zespolu = 2;
UPDATE Zespoly SET Kierownik = 4 WHERE Nr_zespolu = 3;
UPDATE Zespoly SET Kierownik = 7 WHERE Nr_zespolu = 4;

-- Ustawienie szefów działów
UPDATE Dzialy SET Szef_dzialu = 1 WHERE Nr_dzialu = 1;
UPDATE Dzialy SET Szef_dzialu = 4 WHERE Nr_dzialu = 2;
UPDATE Dzialy SET Szef_dzialu = 2 WHERE Nr_dzialu = 3;


-- ============================================================
-- Zadanie 4: Usunięcie pola Specjalizacja z tabeli Zespoly
-- ============================================================

-- W Base (zależnie od silnika/sterownika) DROP COLUMN bywa niedostępne.
-- Najbardziej przenośny sposób: tworzymy tabelę zastępczą bez kolumny Specjalizacja,
-- kopiujemy dane i podmieniamy tabelę.

CREATE TABLE Zespoly_tmp (
    Nr_zespolu INTEGER PRIMARY KEY,
    Nazwa_zespolu VARCHAR(100) NOT NULL UNIQUE,
    Data_powolania DATE NOT NULL,
    Budzet DECIMAL(12,2) NOT NULL,
    Kierownik INTEGER,
    Nr_dzialu INTEGER,
    CONSTRAINT FK_Zespoly_tmp_Dzialy FOREIGN KEY (Nr_dzialu) REFERENCES Dzialy(Nr_dzialu),
    CONSTRAINT FK_Zespoly_tmp_Kierownik FOREIGN KEY (Kierownik) REFERENCES Pracownicy(Nr_prac)
);

INSERT INTO Zespoly_tmp (Nr_zespolu, Nazwa_zespolu, Data_powolania, Budzet, Kierownik, Nr_dzialu)
SELECT Nr_zespolu, Nazwa_zespolu, Data_powolania, Budzet, Kierownik, Nr_dzialu
FROM Zespoly;

-- Najpierw usuwamy zależność z Pracownicy -> Zespoly (FK)
ALTER TABLE Pracownicy DROP CONSTRAINT FK_Pracownicy_Zespoly;

DROP TABLE Zespoly;

ALTER TABLE Zespoly_tmp RENAME TO Zespoly;

-- Odtwarzamy FK z Pracownicy do Zespoly
ALTER TABLE Pracownicy
    ADD CONSTRAINT FK_Pracownicy_Zespoly FOREIGN KEY (Nr_zespolu) REFERENCES Zespoly(Nr_zespolu);


-- ============================================================
-- Zadanie 5: Usunięcie po 1 rekordzie z dwóch tabel
-- ============================================================

-- Usunięcie 1 rekordu z Pracownicy (osoba bez roli kierownika/szefa)
DELETE FROM Pracownicy WHERE Nr_prac = 5;

-- Usunięcie 1 rekordu z Zespoly (zespół samodzielny, bez przypisanego działu)
DELETE FROM Zespoly WHERE Nr_zespolu = 4;


-- ============================================================
-- Zadania SELECT (6-15)
-- ============================================================

-- 6) Imiona i nazwiska pracowników zarabiających co najmniej 4489.34 zł
SELECT Imie, Nazwisko
FROM Pracownicy
WHERE Zarobki >= 4489.34;

-- 7) Lista pracowników z nazwami przypisanych zespołów
SELECT p.Imie, p.Nazwisko, z.Nazwa_zespolu
FROM Pracownicy p
LEFT JOIN Zespoly z ON z.Nr_zespolu = p.Nr_zespolu;

-- 8) Lista działów wraz z nazwiskami ich szefów
SELECT d.Nazwa AS Dzial, p.Nazwisko AS Szef
FROM Dzialy d
JOIN Pracownicy p ON p.Nr_prac = d.Szef_dzialu;

-- 9) Nazwy działów bez przyporządkowanego zespołu
SELECT d.Nazwa
FROM Dzialy d
LEFT JOIN Zespoly z ON z.Nr_dzialu = d.Nr_dzialu
WHERE z.Nr_zespolu IS NULL;

-- 10) Nazwiska pracowników niebędących szefem żadnego działu
SELECT p.Nazwisko
FROM Pracownicy p
LEFT JOIN Dzialy d ON d.Szef_dzialu = p.Nr_prac
WHERE d.Nr_dzialu IS NULL;

-- 11) Nazwiska i zarobki kierowników zespołów zatrudnionych po roku {X1}
-- Przykład: X1 = 2001
SELECT p.Nazwisko, p.Zarobki
FROM Pracownicy p
JOIN Zespoly z ON z.Kierownik = p.Nr_prac
WHERE EXTRACT(YEAR FROM p.Data_zatrudnienia) > 2001;

-- 12) Nazwiska osób będących jednocześnie kierownikiem zespołu i szefem działu
SELECT DISTINCT p.Nazwisko
FROM Pracownicy p
JOIN Zespoly z ON z.Kierownik = p.Nr_prac
JOIN Dzialy d ON d.Szef_dzialu = p.Nr_prac;

-- 13) Imiona i nazwiska osób w zespołach o budżecie > {X2}
-- Przykład: X2 = 16000
SELECT p.Imie, p.Nazwisko
FROM Pracownicy p
JOIN Zespoly z ON z.Nr_zespolu = p.Nr_zespolu
WHERE z.Budzet > 16000;

-- 14) Osoby doświadczone dla zespołu (zatrudnione przed datą powołania zespołu)
SELECT p.Imie, p.Nazwisko, z.Nazwa_zespolu
FROM Pracownicy p
JOIN Zespoly z ON z.Nr_zespolu = p.Nr_zespolu
WHERE p.Data_zatrudnienia < z.Data_powolania;

-- 15) Osoby na stanowisku {X3} w zespołach z budżetem <= {X4}
-- Przykład: X3 = 'programista', X4 = 3000
SELECT p.Imie, p.Nazwisko
FROM Pracownicy p
JOIN Zespoly z ON z.Nr_zespolu = p.Nr_zespolu
WHERE LOWER(p.Stanowisko) = LOWER('programista')
  AND z.Budzet <= 3000;
